Repository potato-marketplace/potato-market-back, pull requests merged in 2022-12, with the labels that each got.

#5 FEAT: 스프링 시큐리티, 예외처리, build-gradle 추가 (#3, #4)
  build.gradle
  src/main/java/com/mini/potatomarket/config/WebSecurityConfig.java
  src/main/java/com/mini/potatomarket/dto/SecurityExceptionDto.java
  src/main/java/com/mini/potatomarket/entity/User.java
  src/main/java/com/mini/potatomarket/entity/UserRoleEnum.java
  src/main/java/com/mini/potatomarket/repository/UserRepository.java
  src/main/java/com/mini/potatomarket/util/error/CustomException.java
  src/main/java/com/mini/potatomarket/util/error/ErrorCode.java
  src/main/java/com/mini/potatomarket/util/error/ErrorResponse.java
  src/main/java/com/mini/potatomarket/util/error/GlobalExceptionHandler.java
  src/main/java/com/mini/potatomarket/util/jwt/JwtAuthFilter.java
  src/main/java/com/mini/potatomarket/util/jwt/JwtUtil.java
  src/main/java/com/mini/potatomarket/util/security/UserDetailsImpl.java
  src/main/java/com/mini/potatomarket/util/security/UserDetailsServiceImpl.java
Labels: enhancement

#6 FEAT : User 객체 오류 수정
  src/main/java/com/mini/potatomarket/entity/User.java
  src/main/java/com/mini/potatomarket/repository/UserRepository.java
  src/main/java/com/mini/potatomarket/util/security/UserDetailsImpl.java
  src/main/java/com/mini/potatomarket/util/security/UserDetailsServiceImpl.java
Labels: enhancement

#12 FEAT: 댓글 및 대댓글 기능 구현 API (#10)
  src/main/java/com/mini/potatomarket/controller/CommentController.java
  src/main/java/com/mini/potatomarket/dto/CommentRequestDto.java
  src/main/java/com/mini/potatomarket/dto/CommentResponseDto.java
  src/main/java/com/mini/potatomarket/entity/Comment.java
  src/main/java/com/mini/potatomarket/entity/Timestamped.java
  src/main/java/com/mini/potatomarket/repository/CommentRepository.java
  src/main/java/com/mini/potatomarket/service/CommentService.java
  src/main/java/com/mini/potatomarket/util/error/ErrorCode.java
Labels: enhancement

#14 Feat : 게시글 CRUD 구현 대댓글 제외
  src/main/java/com/mini/potatomarket/controller/ProductController.java
  src/main/java/com/mini/potatomarket/dto/ProductRequestDto.java
  src/main/java/com/mini/potatomarket/dto/ProductResponseDto.java
  src/main/java/com/mini/potatomarket/dto/ResponseMsgDto.java
  src/main/java/com/mini/potatomarket/entity/Product.java
  src/main/java/com/mini/potatomarket/entity/Timestamped.java
  src/main/java/com/mini/potatomarket/repository/ProductRepository.java
  src/main/java/com/mini/potatomarket/service/ProductService.java
Labels: enhancement

#16 Feat : 전체 게시글, 게시글 선택 조회시 대댓글 출력 기능 추가
  src/main/java/com/mini/potatomarket/dto/CommentRequestDto.java
  src/main/java/com/mini/potatomarket/dto/CommentResponseDto.java
  src/main/java/com/mini/potatomarket/dto/ProductResponseDto.java
  src/main/java/com/mini/potatomarket/entity/Comment.java
  src/main/java/com/mini/potatomarket/entity/Product.java
  src/main/java/com/mini/potatomarket/repository/ProductRepository.java
  src/main/java/com/mini/potatomarket/service/CommentService.java
  src/main/java/com/mini/potatomarket/service/ProductService.java
Labels: enhancement

#17 FEAT : 예외 처리 세부 수정, 전반적 세부 수정 (#8)
  src/main/java/com/mini/potatomarket/config/WebSecurityConfig.java
  src/main/java/com/mini/potatomarket/controller/UserController.java
  src/main/java/com/mini/potatomarket/dto/SecurityExceptionDto.java
  src/main/java/com/mini/potatomarket/dto/SignupRequestDto.java
  src/main/java/com/mini/potatomarket/entity/User.java
  src/main/java/com/mini/potatomarket/entity/UserRoleEnum.java
  src/main/java/com/mini/potatomarket/service/CommentService.java
  src/main/java/com/mini/potatomarket/service/UserService.java
  src/main/java/com/mini/potatomarket/util/error/ErrorCode.java
  src/main/java/com/mini/potatomarket/util/error/GlobalExceptionHandler.java
  src/main/java/com/mini/potatomarket/util/jwt/JwtAuthFilter.java
  src/main/java/com/mini/potatomarket/util/jwt/JwtUtil.java
  src/main/java/com/mini/potatomarket/util/security/UserDetailsImpl.java
Labels: documentation

#19 ProductService Dto 수정
  src/main/java/com/mini/potatomarket/controller/ProductController.java
  src/main/java/com/mini/potatomarket/dto/ProductResponseDto.java
  src/main/java/com/mini/potatomarket/entity/Product.java
  src/main/java/com/mini/potatomarket/service/ProductService.java
Labels: enhancement

#22 Fix : api url 계층 구조로 수정, auditing을 위한 annotaion 추가
  src/main/java/com/mini/potatomarket/PotatoMarketApplication.java
  src/main/java/com/mini/potatomarket/controller/ProductController.java
Labels: enhancement

#24 CHORE : 중복되는 dto 파일 삭제
  src/main/java/com/mini/potatomarket/controller/ProductController.java
  src/main/java/com/mini/potatomarket/dto/ProductResponseDto.java
  src/main/java/com/mini/potatomarket/dto/ResponseMsgDto.java
  src/main/java/com/mini/potatomarket/entity/Product.java
  src/main/java/com/mini/potatomarket/repository/ProductRepository.java
  src/main/java/com/mini/potatomarket/service/ProductService.java
Labels: enhancement

#25 FEAT: 댓글 및 대댓글 API 수정(#20)
  src/main/java/com/mini/potatomarket/controller/CommentController.java
  src/main/java/com/mini/potatomarket/dto/CommentResponseDto.java
  src/main/java/com/mini/potatomarket/entity/Comment.java
  src/main/java/com/mini/potatomarket/repository/CommentRepository.java
  src/main/java/com/mini/potatomarket/service/CommentService.java
Labels: bug

#27 Fix : 게시글 작성시 대댓글이 댓글처럼 나오는 오류 수정
  src/main/java/com/mini/potatomarket/dto/CommentResponseDto.java
  src/main/java/com/mini/potatomarket/dto/ProductResponseDto.java
  src/main/java/com/mini/potatomarket/entity/Product.java
  src/main/java/com/mini/potatomarket/repository/CommentRepository.java
  src/main/java/com/mini/potatomarket/service/CommentService.java
  src/main/java/com/mini/potatomarket/service/ProductService.java
Labels: enhancement

#29 DOCS: application 파일 properties -> yml 로 변경
  .gitignore
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: documentation

#31 FEAT: AWS S3를 이용한 다중 이미지 업로드 API 구현
  .gitignore
  build.gradle
  src/main/java/com/mini/potatomarket/config/AwsS3Config.java
  src/main/java/com/mini/potatomarket/controller/AwsS3Controller.java
  src/main/java/com/mini/potatomarket/controller/ProductController.java
  src/main/java/com/mini/potatomarket/dto/ImageFileRequestDto.java
  src/main/java/com/mini/potatomarket/dto/ImageFileResponseDto.java
  src/main/java/com/mini/potatomarket/dto/ProductResponseDto.java
  src/main/java/com/mini/potatomarket/entity/ImageFile.java
  src/main/java/com/mini/potatomarket/entity/Product.java
  src/main/java/com/mini/potatomarket/repository/ImageFileRepository.java
  src/main/java/com/mini/potatomarket/service/AwsS3Service.java
  src/main/java/com/mini/potatomarket/service/ProductService.java
  src/main/resources/application.yml
Labels: enhancement

#33 FEAT : 불필요한 주석 제거 및 연관 관계 수정 (#32)
  src/main/java/com/mini/potatomarket/controller/UserController.java
  src/main/java/com/mini/potatomarket/entity/User.java
Labels: documentation

#35 CHORE : cors 추석 처리 상태로 추가
  src/main/java/com/mini/potatomarket/config/WebSecurityConfig.java
Labels: documentation

#41 REFACTOR : 에러코드 수정 (#39)
  src/main/java/com/mini/potatomarket/controller/UserController.java
  src/main/java/com/mini/potatomarket/entity/User.java
  src/main/java/com/mini/potatomarket/repository/UserRepository.java
  src/main/java/com/mini/potatomarket/service/UserService.java
  src/main/java/com/mini/potatomarket/util/error/ErrorCode.java
  src/main/java/com/mini/potatomarket/util/error/ErrorResponse.java
  src/main/java/com/mini/potatomarket/util/error/GlobalExceptionHandler.java
Labels: documentation

#44 CORS 오류 해결을 위한 Access-Control-Allow-Origin 헤더 세팅
  src/main/java/com/mini/potatomarket/config/WebSecurityConfig.java
Labels: bug
